config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # view
  #
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: %i[new create]
  end

  resources :movies # , only: %i[new create destroy]

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id, message: "already in the list" }
  validates :comment, length: { minimum: 6, too_short: '%<count> characters is the minimum allowed' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
  validates :name, length: { maximum: 50 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one :list

  validates :title, uniqueness: true, presence: true, length: { maximum: 100 }
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_find_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to lists_path(@list.id)
    else
      render :new
    end
  end

  def edit; end

  def update
    @list.update(params_list)
    redirect_to lists_path(@list.id)
  end

  def show
    @bookmark = Bookmark.new
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end

  def set_find_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_find_movie, only: %i[show edit update destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params_list)
    if @movie.save
      redirect_to movie_path(@movie.id)
    else
      render :new
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private

  def params_list
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end

  def set_find_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new list</h1>

      <div class="mt-3">
        <%= render "form", list: @list %>
      </div>

      <hr>
      <br><br>
      <%= link_to 'Back to list', '/lists' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <h1>Save any kind of movies</h1>
    <h3 class="typed-js"></h3>
  </div>
</div>

<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to 'Create a movie list', new_list_path, class: 'btn btn-flat' %>
  </div>

  <div class="row">

    <% @lists.each do |item| %>
      <div class="co-12 colsm-6 col-md-4">

        <%= link_to list_path(item), class: 'text-decoration-none' do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('list_background.jpg') %>)">
            <%= item.name %>
          </div>
          <br>
        <% end %>
      </div>
    <% end %>

  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <hr>
      <%= link_to 'Create a movie list', 'lists/new', class: 'btn btn-flat' %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <h3>Create a new list</h3>

      <div class="mt-3">
        <%= render "form", list: @list %>
      </div>

      <hr>
      <br><br>
      <%= link_to 'Back to list', '/lists' %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('list_background.jpg') %>)">
    <h1><%= @list.name %>&nbsp; &nbsp; </h1>
    <small>
      <%= link_to "#{@list.id}/edit", :method => :get, :title => "Update  #{@list.name}" do %>
        <i class="fas fa-pencil-alt"></i>
      <% end %>
    </small>
    &nbsp;
    <small>

      <%= link_to @lists, :method => :delete, :title => "Delete #{@list.name}", data: { :confirm => "You sure?", disable_with: "Processing ..." } do %>
        <i class="fas fa-trash"></i>
      <% end %>

    </small>

  </div>
  <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>

<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <%= link_to 'add a movie', new_movie_path(@movie), class: 'btn btn-flat' %>
      <%= link_to 'delete this list', list_path(@list), method: :delete, class: 'btn btn-cancel', data: { confirm: 'Are you sure you want to delete this list?' } %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: 'movie-img rounded-top' %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %>
              <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list" }, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr class="my-5">


  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <br>
        <%= link_to "back to list", '/lists' %>
      </div>
    </div>
  </div>